results= [];
bins = [2 3 4 5 6 7 8 9 10];
hist(results , bins);
xlabel("Victory Points");
ylabel("Frequency");
numResults = length(results);
axis([2 10 0 numResults/2]);
title("Results of 100 Simulation play");
avg = mean(results);
dev = std(results);
